USE master;
GO

IF DB_ID('User_Data') IS NOT NULL
BEGIN
    ALTER DATABASE User_Data SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE User_Data;
END
GO

CREATE DATABASE User_Data;
GO

USE User_Data;
GO

CREATE TABLE Roles (
    ID INT PRIMARY KEY,
    Name NVARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE Users (
    ID INT IDENTITY PRIMARY KEY,
    Email NVARCHAR(100) NOT NULL UNIQUE,
    PasswordHash NVARCHAR(255) NOT NULL,
    RoleID INT NOT NULL,
    CreatedAt DATETIME2 DEFAULT SYSDATETIME(),
    CONSTRAINT FK_Users_Roles FOREIGN KEY (RoleID) REFERENCES Roles(ID)
);

INSERT INTO Roles (ID, Name) VALUES
(1, N'Admin'),
(2, N'Seller'),
(3, N'User');

GO
